---
#- hosts: hosts
#- become: yes
#- tasks:
  - name: Copy containerd.rpm and kuber
    ansible.builtin.copy:
      src: files/{{ item }}
      dest: /tmp/{{ item }}
    with_items:
    - containerd.io-1.6.24-3.1.el9.x86_64.rpm
#    - docker-buildx-plugin-0.11.2-1.el9.x86_64.rpm
#    - docker-ce-24.0.7-1.el9.x86_64.rpm
#    - docker-ce-cli-24.0.7-1.el9.x86_64.rpm
#    - docker-ce-rootless-extras-24.0.7-1.el9.x86_64.rpm
 #   - docker-compose-plugin-2.21.0-1.el9.x86_64.rpm
    - conntrack-tools-1.4.7-2.el9.x86_64.rpm
    - cri-tools-1.26.0-0.x86_64.rpm
    - kubeadm-1.28.2-0.x86_64.rpm
    - kubectl-1.28.2-0.x86_64.rpm
    - kubelet-1.28.2-0.x86_64.rpm
    - kubernetes-cni-1.2.0-0.x86_64.rpm
    - libnetfilter_cthelper-1.0.0-22.el9.x86_64.rpm
    - libnetfilter_cttimeout-1.0.0-19.el9.x86_64.rpm
    - libnetfilter_queue-1.0.5-1.el9.x86_64.rpm
    - socat-1.7.4.1-5.el9.x86_64.rpm

  - name: Install containerd and kuber
    shell: yum localinstall /tmp/*.rpm  -y
    register: installpackageother
    ignore_errors: True

  - name: Install containerd and kuber repo
    shell: yum install -y containerd  kubeadm kubelet kubectl
    when: installpackageother.rc != 0
  
  
  - name: containered edit config
    ansible.builtin.copy:
      src: files/containerd.toml
      dest: /etc/containerd/config.toml
  - name: containered service start
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: true
      enabled: true
      name: containerd
#  - name: docker service start
#    ansible.builtin.systemd:
#      state: restarted
#      daemon_reload: true
 #     enabled: true
  #    name: docker
  - name: firewall service stop
    ansible.builtin.systemd:
      state: stopped
      enabled: false
      name: firewalld
    ignore_errors: True
 # - name: Install Kubernetes packages
 #   shell: yum localinstall -y /tmp/*.rpm
  - name: kebelet service start
    ansible.builtin.systemd:
      state: restarted
      daemon_reload: true
      enabled: true
      name: kubelet
