---
#- hosts: hosts
#- become: yes
#- tasks:
  - name: Set host name
    shell: hostnamectl set-hostname {{ hostname }}
  - name: Generate hosts files
    template:
      src=files/hosts.j2
      dest=/etc/hosts
  - name: Swap conf off
    shell: sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
  - name: Swap off
    shell: swapoff -a
    ignore_errors: True
  - name: Selinux conf off
    shell: sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  - name: Selinux off
    shell: setenforce 0
    ignore_errors: True
  - name: Add modules
    copy: 
      dest: /etc/modules-load.d/k8s.conf
      content: |
         overlay
         br_netfilter
  - name: Add sysctl
    copy: 
      dest: /etc/sysctl.d/k8s.conf
      content: |
         net.ipv4.ip_forward=1
         net.bridge.bridge-nf-call-ip6tables=1
         net.bridge.bridge-nf-call-iptables=1
  - name : Apply sysctl
    shell: sysctl --system
    ignore_errors: True
